services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bbmri-it-school
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "bbmri-it-school" ]
      interval: 5s
      timeout: 60s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./omop.sql:/docker-entrypoint-initdb.d/omop.sql
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bbmri-school.it
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  db-data:
  pgadmin-data: